[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
silksol_escrow = "Gu7gKXNnp95qTvaDwoq3NB9JCqBQLmriHQgKrFzJAr9Z"

[programs.devnet]
silksol_escrow = "Gu7gKXNnp95qTvaDwoq3NB9JCqBQLmriHQgKrFzJAr9Z"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --test --experimental-strip-types tests/*.test.ts"
